version: '3.8'

services:
  web:
    #build: .
    image: oncall_scheduler_app_web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SQLALCHEMY_ECHO=True
      - SECRET_KEY=your_secret_key
      - DB_HOST=db
      - PORT=5000
    secrets:
      - db_user
      - db_password
      - db_name
      - srs_user
      - srs_password
    #depends_on:
    #  - db

# db:
#   image: postgres:13
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: oncall_scheduler
#    secrets:
#      - db_user
 #     - db_password
#      - db_name

#volumes:
#  postgres_data:

secrets:
  db_user:
   external: true
  db_password:
    external: true
  db_name:
    external: true
  srs_user:
    external: true
  srs_password:
   external: true
      
